import type { Metadata } from "next";
import { PT_Sans } from "next/font/google";
import "./globals.css";
import '@splidejs/react-splide/css';
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import LoaderWrapper from "./components/Loader";
import CustomSpeedDial from "./components/CustomSpeedDial";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const PTSans = PT_Sans({
  weight: ["400","700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "The Non Coders",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${PTSans.className} antialiased`}>
        <AppRouterCacheProvider>
          <LoaderWrapper fadeDuration={1500} showDuration={3000}>
            <Header />
            {children}
            <ToastContainer position="top-right" autoClose={3000} />
            <CustomSpeedDial />
            <Footer />
          </LoaderWrapper>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
